fix timeout diagnostics for namespaces
in case of timeouts related to a namespace we had errors like:
"sequence item 5: expected str instance, NoneType found"
e.g.
  File "/export/home/tmp/jenkins_workspace/workspace/Shell/KubernetesOperator/workers/k3d/tests/utils/kutil.py", line 239, in __ls
    return split_table(kubectl("get", rsrc, args=["-n", ns], ignore=ignore).stdout.decode("utf8"))
  File "/export/home/tmp/jenkins_workspace/workspace/Shell/KubernetesOperator/workers/k3d/tests/utils/kutil.py", line 116, in kubectl
    logger.debug("run %s", " ".join(argv))
TypeError: sequence item 5: expected str instance, NoneType found

it expected a namespace in args
args=["-n", ns]
but ns is not included in another namespace, hence ns from args was None in such calls

Change-Id: I960f7a2d7d7e6911184d143ecb7dd1549929b234