MYF-215: All Tests have to be green
fixes in init_db_t.ClusterFromDumpOCI:
- proper prefix in OCI-related yamls
- some code commented due to:
 _mysql_connector.MySQLInterfaceError: Cannot modify @@session.sql_log_bin inside a transaction

Change-Id: Ia836f9ce1038422c334b5f75a07ca92deb857880