fix weekly failure at calling a shell cmd
jenkins may fails due to calling a shell command that copes with
a directory with plenty of files
it is somewhat weird but that's what we've experienced
during weekly builds #80-84:
Error when executing cleanup post condition:
java.io.IOException: error=7, Argument list too long

a new command scans only a few the most important files in
the log dir

Change-Id: I2795ee0926ebe3164d485f3306d2daf47e8274bf